// .Resumen {
//   overflow: auto;
//   display: flex;
//   flex-direction: column;
//   background-color: #161616;
//   border-radius: 1rem;
//   padding: 1.5rem;
//   width: 100%;
//   height: 100%;

//   @media screen and (width < 768px) {
//     border-radius: 1.25rem;
//     border-top-left-radius: 0;
//     border-top-right-radius: 0;
//     padding: 0 1rem;
//   }
// }

.Resumen {
  container-type: inline-size;
}

.overviewTitle {
  display: flex;
  align-self: center;
  color: #424242;
  font-size: 2.5rem;
  font-style: normal;
  font-weight: 600;
  line-height: 3rem;
  letter-spacing: -0.01875rem;
  width: 100%;

  @media screen and (width < 768px) {
    font-size: 2rem;
    letter-spacing: -0.031rem;
    line-height: 2.5rem;
    padding-top: 1rem;
  }

  span {
    color: #fff;
  }
}

.overviewGrid {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  grid-template-rows: 190px 190px 1fr 1fr;
  grid-template-areas:
    'stats stats dateTime dateTime unknown1 unknown1'
    'stats stats restriction restriction unknown1 unknown1'
    'examenes examenes modalidades modalidades unknown2 unknown2'
    'examenes examenes modalidades modalidades unknown2 unknown2';
  column-gap: 0.625rem;
  row-gap: 0.625rem;
  align-self: center;
  padding-top: 1.5rem;
  // height: 100%;
  max-width: 1280px;
  width: 100%;
}

#StatisticsCard {
  grid-area: stats;
}

#DateTimeCard {
  grid-area: dateTime;
}

#RestrictionCard {
  grid-area: restriction;
}

#Unknown1 {
  grid-area: unknown1;
}

#ExamsCard {
  grid-area: examenes;
}

#ModesCard {
  grid-area: modalidades;
}

#NotesCard {
  grid-area: unknown2;
}

.examenesCard,
.modalidadesCard,
.dailyQuestionCard {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-end;
  background-color: #1e1e1e;
  border-radius: 1.875rem;
  color: #8c8c8c;
  padding: 1.125rem;
}

#ExamCard {
  grid-column: 1 / 3;
  grid-row: 3 / 5;
}

.modalidadesCard {
  grid-column: 3 / 5;
  grid-row: 3 / 5;
}

.notesCard {
  grid-column: 5 / 7;
  grid-row: 1 / 2;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-start;
  // background-color: #1E1E1E;
  border-radius: 1.875rem;
  color: #8c8c8c;
  // padding: 1.125rem;

  .planWrapper {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: flex-end;
    background-color: #1e1e1e;
    border-radius: 1.375rem;
    padding: 1.125rem;
    width: 100%;

    .planName,
    .expirateDate {
      color: #ffb300;
      font-size: 2rem;
      font-weight: 500;
      letter-spacing: -0.031rem;
      line-height: 2.5rem;
    }
  }
}

.dailyQuestionCard {
  grid-column: 5 / 7;
  grid-row: 3 / 5;
}

@container (width < 1280px) {
  .overviewTitle {
    max-width: 850px;
  }

  .overviewGrid {
    grid-template-columns: repeat(4, 1fr);
    // grid-template-rows: repeat(6, 1fr);
    grid-template-rows: 190px 190px 1fr 1fr 1fr 1fr;
    grid-template-areas:
      'stats stats dateTime dateTime'
      'stats stats restriction restriction'
      'unknown1 unknown1 unknown1 unknown1'
      'examenes examenes modalidades modalidades'
      'unknown2 unknown2 unknown2 unknown2';
    max-width: 850px;
  }
}

@container (width < 850px) {
  .overviewGrid {
    grid-template-columns: repeat(2, 1fr);
    // grid-template-rows: repeat(6, 1fr);
    grid-template-rows: 160px 160px 150px 150px auto repeat(3, 1fr);
    grid-template-areas:
      'stats stats'
      'stats stats'
      'dateTime dateTime'
      'restriction restriction'
      'unknown1 unknown1'
      'examenes examenes'
      'modalidades modalidades'
      'unknown2 unknown2';
  }
}

.cardTitle {
  color: #fff;
  font-size: 1.5rem;
  font-weight: 600;
  letter-spacing: -0.031rem;
  line-height: 2rem;
  // padding-top: 1.375rem;
  padding-bottom: 0.625rem;
}
